-- Add content scheduling fields to posts table
ALTER TABLE public.posts 
ADD COLUMN IF NOT EXISTS scheduled_publish_at timestamptz,
ADD COLUMN IF NOT EXISTS ai_persona_id uuid,
ADD COLUMN IF NOT EXISTS generation_prompt text,
ADD COLUMN IF NOT EXISTS auto_generated boolean DEFAULT false;

-- Add index for scheduled posts query performance
CREATE INDEX IF NOT EXISTS idx_posts_scheduled_publish_at 
ON public.posts(scheduled_publish_at) 
WHERE scheduled_publish_at IS NOT NULL AND published = false;

-- Add comment for documentation
COMMENT ON COLUMN public.posts.scheduled_publish_at IS 'Timestamp when the post should be automatically published';
COMMENT ON COLUMN public.posts.ai_persona_id IS 'Reference to the AI persona that generated this content';
COMMENT ON COLUMN public.posts.generation_prompt IS 'The prompt used to generate this content';
COMMENT ON COLUMN public.posts.auto_generated IS 'Whether this post was automatically generated by AI';